CREATE OR REPLACE VIEW VPI.VIEW_WASH_ISTR_DOCUMENT AS
SELECT
	I.CYCLE_ID,
	I.ISTR_ID,
	I.ISTR_ORDER,
	I.ISTR_TYPE,
	DECODE(I.ISTR_TYPE, 'DELETE', NULL, 'COPY', C.SRC_VIEW, 'MERGE', M.SRC_VIEW)			AS SRC_VIEW,
	DECODE(I.ISTR_TYPE, 'DELETE', NULL, 'COPY', C.SRC_FILTER, 'MERGE', M.SRC_FILTER)		AS SRC_FILTER,
	DECODE(I.ISTR_TYPE, 'DELETE', D.DST_TABLE, 'COPY', C.DST_TABLE, 'MERGE', M.DST_TABLE)	AS DST_TABLE,
	DECODE(I.ISTR_TYPE, 'DELETE', D.DST_FILTER, 'COPY', NULL, 'MERGE', NULL)				AS DST_FILTER,
	DECODE(I.ISTR_TYPE, 'DELETE', NULL, 'COPY', NULL, 'MERGE', M.JOIN_COLUMNS)				AS JOIN_COLUMNS,
	DECODE(I.ISTR_TYPE, 'DELETE', NULL, 'COPY', NULL, 'MERGE', M.UPDATE_COLUMNS)			AS UPDATE_COLUMNS,
	DECODE(I.ISTR_TYPE, 'DELETE', NULL, 'COPY', NULL, 'MERGE', M.INSERT_COLUMNS)			AS INSERT_COLUMNS,
	I.DESCRIPTION_
FROM
	VPI.WASH_ISTR			I
LEFT JOIN
	VPI.WASH_ISTR_DELETE	D
ON (D.ISTR_ID	= I.ISTR_ID)
LEFT JOIN
	VPI.WASH_ISTR_COPY		C
ON (C.ISTR_ID	= I.ISTR_ID)
LEFT JOIN
	VPI.WASH_ISTR_MERGE		M
ON (M.ISTR_ID	= I.ISTR_ID)
ORDER BY
	I.CYCLE_ID,
	I.ISTR_ORDER

WITH READ ONLY;
