CREATE OR REPLACE VIEW VPI.VIEW_WASH_LAST_PROGRESS_LOG AS
SELECT
	LOG_TIME,
	PROGRESS_ID,
	CURRENT_STEP,
	CURRENT_STATUS,
	SPENT_TIME
FROM
	VPI.VIEW_PROGRESS_LOG
WHERE
	PROGRESS_ID	= (SELECT MAX(PROGRESS_ID) KEEP (DENSE_RANK FIRST ORDER BY REGISTER_TIME DESC) FROM VPI.WASH_PROGRESS)

WITH READ ONLY;
