CREATE OR REPLACE VIEW VPI.VIEW_WASH_CYCLE_CODE AS
SELECT
	CYCLE_ID,
	PROCEDURE_NAME,
	VPI.WASH_ENGINE.GEN_PROCEDURE(CYCLE_ID)		AS PROCEDURE_CODE,
	DESCRIPTION_,
	OWNER_
FROM
	VPI.WASH_CYCLE

WITH READ ONLY;
