CREATE OR REPLACE TRIGGER VPI.TRG_WASH_ISTR
BEFORE INSERT OR UPDATE ON VPI.WASH_ISTR
FOR EACH ROW
DECLARE
	tISTR_ID	VARCHAR2(32) := UPPER(TRIM(:new.ISTR_ID));
BEGIN
	IF tISTR_ID != :new.ISTR_ID THEN
		:new.ISTR_ID := tISTR_ID;
	END IF;
END;
/
