CREATE OR REPLACE TRIGGER VPI.TRG_CACHE_CONTROL
BEFORE INSERT ON VPI.CACHE_CONTROL
FOR EACH ROW
BEGIN
	IF :new.LOCK_ORDINAL IS NULL THEN
		:new.LOCK_ORDINAL := VPI.SEQ_CACHE_LOCK_ORDINAL.NEXTVAL;
	END IF;
END;
/
