CREATE TABLE VPI.PROGRESS_LOG
(
	PROGRESS_ID		NUMBER(9)		NOT NULL,
	LOG_TIME		TIMESTAMP(3)	DEFAULT SYSTIMESTAMP	NOT NULL,
	CURRENT_STEP	NUMBER(5)								NOT NULL,
	CURRENT_STATUS	VARCHAR2(256)
)	COMPRESS;

CREATE INDEX VPI.IX_PROGRESS_LOG ON VPI.PROGRESS_LOG (PROGRESS_ID, LOG_TIME, CURRENT_STEP) COMPRESS;
