CREATE TABLE VPI.WASH_CYCLE
(
	CYCLE_ID		VARCHAR2(32)		NOT NULL,	-- Globel name
	PROCEDURE_NAME	VARCHAR2(61)		NOT NULL,
	DESCRIPTION_	VARCHAR2(512),
	OWNER_			VARCHAR2(32),
	LATEST_VERSION	NUMBER(4) DEFAULT 0	NOT NULL,

	CONSTRAINT PK_WASH_CYCLE PRIMARY KEY (CYCLE_ID),
	CONSTRAINT UK_WASH_CYCLE_SP UNIQUE (PROCEDURE_NAME),
	CONSTRAINT CK_WASH_CYCLE_VER CHECK (LATEST_VERSION >= 0)
)	STORAGE (INITIAL 16K NEXT 16K);
