CREATE TABLE VPI.WASH_ISTR_TYPE
(
	ISTR_TYPE		VARCHAR2(16)		NOT NULL,
	DERIVED_TABLE	VARCHAR2(30)		NOT NULL,
	TYPE_BRIEF		VARCHAR2(32)		NOT NULL,
	DESCRIPTION_	VARCHAR2(128),

	CONSTRAINT PK_WASH_ISTR_TYPE PRIMARY KEY (ISTR_TYPE),
	CONSTRAINT UK_WASH_ISTR_TYPE_DT UNIQUE (DERIVED_TABLE),
	CONSTRAINT CK_WASH_ISTR_TYPE_T CHECK (ISTR_TYPE = UPPER(TRIM(ISTR_TYPE)))
)	STORAGE (INITIAL 16K NEXT 8K);
