CREATE TABLE VPI.WASH_ISTR
(
	ISTR_ID			VARCHAR2(32)		NOT NULL,
	CYCLE_ID		VARCHAR2(32)		NOT NULL,
	ISTR_TYPE		VARCHAR2(16)		NOT NULL,
	ISTR_ORDER		NUMBER(4) DEFAULT 0	NOT NULL,
	DESCRIPTION_	VARCHAR2(1024),

	CONSTRAINT PK_WASH_ISTR PRIMARY KEY (ISTR_ID),
	CONSTRAINT FK_WASH_ISTR_C FOREIGN KEY (CYCLE_ID) REFERENCES VPI.WASH_CYCLE (CYCLE_ID) ON DELETE CASCADE,
	CONSTRAINT FK_WASH_ISTR_T FOREIGN KEY (ISTR_TYPE) REFERENCES VPI.WASH_ISTR_TYPE (ISTR_TYPE)
);

CREATE INDEX VPI.IX_WASH_ISTR_ODR ON VPI.WASH_ISTR (CYCLE_ID, ISTR_ORDER);
CREATE INDEX VPI.IX_WASH_ISTR_T ON VPI.WASH_ISTR (CYCLE_ID, ISTR_TYPE);
