CREATE TABLE VPI.WASH_DML_PLAN
(
	CYCLE_ID		VARCHAR2(32)			NOT NULL,
	ISTR_ORDER		NUMBER(4)				NOT NULL,
	PLAN_SQL		VARCHAR2(4000)			NOT NULL,
	ISTR_ID			VARCHAR2(32)			NOT NULL,
	ISTR_BRIEF		VARCHAR2(1024),
	PLANNED_TIME	DATE DEFAULT SYSDATE	NOT NULL,

	CONSTRAINT FK_WASH_DML_PLAN_CYCLE FOREIGN KEY (CYCLE_ID) REFERENCES VPI.WASH_CYCLE (CYCLE_ID) ON DELETE CASCADE
);

CREATE INDEX VPI.IX_WASH_DML_PLAN_ORD ON VPI.WASH_DML_PLAN (CYCLE_ID, ISTR_ORDER);
