CREATE TABLE VPI.WASH_ISTR_CHK_UK
(
	ISTR_ID					VARCHAR2(32)		NOT NULL,
	DST_TABLE				VARCHAR2(61)		NOT NULL,	-- Destination Table (must include schema.table)
	DST_FILTER				VARCHAR2(1024),
	KEY_COLUMNS				VARCHAR2(256)		NOT NULL,
	SET_EXPR_IF_UNIQUE		VARCHAR2(1024),
	SET_EXPR_IF_DUPLICATE	VARCHAR2(1024),

	CONSTRAINT PK_WASH_ISTR_CHK_UK PRIMARY KEY (ISTR_ID),
	CONSTRAINT FK_WASH_ISTR_CHK_UK FOREIGN KEY (ISTR_ID) REFERENCES VPI.WASH_ISTR (ISTR_ID) ON DELETE CASCADE,
	CONSTRAINT CK_WASH_ISTR_CHK_UK_DT CHECK (INSTR(DST_TABLE, '.') > 0),
	CONSTRAINT CK_WASH_ISTR_CHK_UK_IF CHECK (SET_EXPR_IF_UNIQUE IS NOT NULL OR SET_EXPR_IF_DUPLICATE IS NOT NULL)
);
