CREATE TABLE VPI.WASH_ISTR_TOP_DK
(
	ISTR_ID			VARCHAR2(32)		NOT NULL,
	DST_TABLE		VARCHAR2(61)		NOT NULL,	-- Destination Table (must include schema.table)
	DST_FILTER		VARCHAR2(1024),
	KEY_COLUMNS		VARCHAR2(256)		NOT NULL,
	ORDER_BY		VARCHAR2(256)		NOT NULL,
	RN_COLUMN		VARCHAR2(30)		NOT NULL,

	CONSTRAINT PK_WASH_ISTR_TOP_DK PRIMARY KEY (ISTR_ID),
	CONSTRAINT FK_WASH_ISTR_TOP_DK FOREIGN KEY (ISTR_ID) REFERENCES VPI.WASH_ISTR (ISTR_ID) ON DELETE CASCADE,
	CONSTRAINT CK_WASH_ISTR_TOP_DK_DT CHECK (INSTR(DST_TABLE, '.') > 0)
);
