CREATE TABLE VPI.WASH_ISTR_MUP_NA
(
	ISTR_ID			VARCHAR2(32)		NOT NULL,
	DST_TABLE		VARCHAR2(61)		NOT NULL,	-- Destination Table (must include schema.table)
	DST_KEY_COLUMNS	VARCHAR2(256)		NOT NULL,
	DST_VAL_COLUMNS	VARCHAR2(512),
	MAKEUP_KEYS		VARCHAR2(256)		NOT NULL,
	MAKEUP_VALUES	VARCHAR2(512),

	CONSTRAINT PK_WASH_ISTR_MUP_NA PRIMARY KEY (ISTR_ID),
	CONSTRAINT FK_WASH_ISTR_MUP_NA FOREIGN KEY (ISTR_ID) REFERENCES VPI.WASH_ISTR (ISTR_ID) ON DELETE CASCADE,
	CONSTRAINT CK_WASH_ISTR_MUP_NA_D CHECK (INSTR(DST_TABLE, '.') > 0)
);
