CREATE TABLE VPI.WASH_ISTR_MUP_MK
(
	ISTR_ID			VARCHAR2(32)		NOT NULL,
	SRC_VIEW		VARCHAR2(61)		NOT NULL,	-- Source View (must include schema.view/table)
	SRC_FILTER		VARCHAR2(1024),
	SRC_KEY_COLUMNS	VARCHAR2(256)		NOT NULL,
	DST_TABLE		VARCHAR2(61)		NOT NULL,	-- Destination Table (must include schema.table)
	DST_KEY_COLUMNS	VARCHAR2(256)		NOT NULL,
	DST_VAL_COLUMNS	VARCHAR2(512),
	SRC_VALUES		VARCHAR2(512),

	CONSTRAINT PK_WASH_ISTR_MUP_MK PRIMARY KEY (ISTR_ID),
	CONSTRAINT FK_WASH_ISTR_MUP_MK FOREIGN KEY (ISTR_ID) REFERENCES VPI.WASH_ISTR (ISTR_ID) ON DELETE CASCADE,
	CONSTRAINT CK_WASH_ISTR_MUP_MK_S CHECK (INSTR(SRC_VIEW, '.') > 0),
	CONSTRAINT CK_WASH_ISTR_MUP_MK_D CHECK (INSTR(DST_TABLE, '.') > 0)
);
