CREATE TABLE VPI.WASH_VERSION
(
	CYCLE_ID			VARCHAR2(32)		NOT NULL,
	VERSION_			NUMBER(4)			NOT NULL,
	PROCEDURE_NAME		VARCHAR2(61)		NOT NULL,
	PROCEDURE_SCRIPT	CLOB				NOT NULL,
	COMMENT_			VARCHAR2(2000),
	DEPLOY_STATUS		NUMBER(1) DEFAULT 0	NOT NULL,
	DEPLOY_ERROR		VARCHAR2(512),

	CONSTRAINT PK_WASH_VERSION PRIMARY KEY (CYCLE_ID, VERSION_),
	CONSTRAINT FK_WASH_VERSION_C FOREIGN KEY (CYCLE_ID) REFERENCES VPI.WASH_CYCLE (CYCLE_ID) ON DELETE CASCADE
);
