CREATE TABLE VPI.WASH_PROGRESS
(
	PROGRESS_ID		NUMBER(9)		NOT NULL,
	CYCLE_ID		VARCHAR2(32)	NOT NULL,
	REGISTER_TIME	TIMESTAMP(3)	DEFAULT SYSTIMESTAMP	NOT NULL,

	CONSTRAINT PK_WASH_PROGRESS PRIMARY KEY (PROGRESS_ID),
	CONSTRAINT FK_WASH_PROGRESS_ID FOREIGN KEY (PROGRESS_ID) REFERENCES VPI.PROGRESS_STATUS (PROGRESS_ID) ON DELETE CASCADE,
	CONSTRAINT FK_WASH_PROGRESS_C FOREIGN KEY (CYCLE_ID) REFERENCES VPI.WASH_CYCLE (CYCLE_ID) ON DELETE CASCADE
);

CREATE INDEX IX_WASH_PROGRESS_T ON VPI.WASH_PROGRESS (REGISTER_TIME);
